### ISSUE TITLE
Black background in geary new message

### ISSUE THREAD

**Issue by anfrantic** [bsundman/Yosembiance#2]
![Image of Yaktocat](http://dl.dropbox.com/u/97132635/Selection_005.png)

Ubuntu 14.04
Geary 0.8

This issue apears only when overlay scrollbars are enabled

**Comment by bsundman** [comment]
Thanks, I'll try to get around to this tonight.

**Comment by anfrantic** [comment]
Adding this hack to gtk-widgets.css

``` css
GtkEventBox {
    background-color: @bg_color;
}
```

seems to solve the problem
