### ISSUE TITLE
Evolution black background fix

### ISSUE THREAD

**Issue by anfrantic** [bsundman/Yosembiance#3]
Same problem as with geary =(

fixed by 

``` css
GtkWindow {
     color: @fg_color;
     background-color: @bg_color;
 }
```
